spring-boot-plus:
  # 是否启用ansi控制台输出有颜色的字体，local环境建议开启，服务器环境设置为false
  enable-ansi: false

spring:
  datasource:
    url:
    username:
    password:

  # Redis配置
  redis:
    database:
    host:
    password:
    port:

